# Generated by Django 4.1.1 on 2022-09-29 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroPalabra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_palabra', models.CharField(max_length=50)),
                ('palabra', models.CharField(max_length=50)),
                ('significado', models.CharField(max_length=500)),
            ],
        ),
    ]
